### PR TITLE
Add new sensors and timers

### PR DESCRIPTION
**Pull request by kntsoft**
Add the fnId of 4 timers and the %LEL gas Sensor

### CODE REVIEW

**Comment by sillyfrog** [comment]
Thanks @kntsoft , would you mind updating this PR with only the required changes please, it looks like the editor went and changed a bunch of formatting as well making the diff quite large.

Cheers.

**Comment by kntsoft** [comment]
> Thanks @kntsoft , would you mind updating this PR with only the required changes please, it looks like the editor went and changed a bunch of formatting as well making the diff quite large.
> 
> Cheers.

I fixed It, I don't know why the Visual Studio Code autoformatted on the save the file.

**Review by sillyfrog — APPROVED** [review]

**Comment by sillyfrog** [comment]
Thanks!

Yeah, it's common for it to format on save, and depending on the formatter depends on how it changes. I'll look to include a `.vscode` config as part of the project when I get a chance.

**Comment by kntsoft** [comment]
Ooo finally you didn't approve the PR. What's the problem?

**Comment by sillyfrog** [comment]
“Wetware” issue trying to go quickly. 😜

Merged now. 😀

**Pull request merged**
